// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEzM2kgUoLOdEGGTbJjqtzsFRSXmSOd90',
    appId: '1:736207474949:web:db1f515e9424c40b6ee76c',
    messagingSenderId: '736207474949',
    projectId: 'thoikhoabieuapp-9f53e',
    authDomain: 'thoikhoabieuapp-9f53e.firebaseapp.com',
    storageBucket: 'thoikhoabieuapp-9f53e.firebasestorage.app',
    measurementId: 'G-XD5NQ4SD2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGY-lcRi9QHqn_0WrOxodNu3eUHXjpcTs',
    appId: '1:736207474949:android:ae4c70454e3a76826ee76c',
    messagingSenderId: '736207474949',
    projectId: 'thoikhoabieuapp-9f53e',
    storageBucket: 'thoikhoabieuapp-9f53e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzzkLpiS07lp98rd2uVQp86MkYHdlwgy4',
    appId: '1:736207474949:ios:00bd1f40fc6427446ee76c',
    messagingSenderId: '736207474949',
    projectId: 'thoikhoabieuapp-9f53e',
    storageBucket: 'thoikhoabieuapp-9f53e.firebasestorage.app',
    iosBundleId: 'com.example.thoikhoabieuapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzzkLpiS07lp98rd2uVQp86MkYHdlwgy4',
    appId: '1:736207474949:ios:00bd1f40fc6427446ee76c',
    messagingSenderId: '736207474949',
    projectId: 'thoikhoabieuapp-9f53e',
    storageBucket: 'thoikhoabieuapp-9f53e.firebasestorage.app',
    iosBundleId: 'com.example.thoikhoabieuapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEzM2kgUoLOdEGGTbJjqtzsFRSXmSOd90',
    appId: '1:736207474949:web:db2562de95db988c6ee76c',
    messagingSenderId: '736207474949',
    projectId: 'thoikhoabieuapp-9f53e',
    authDomain: 'thoikhoabieuapp-9f53e.firebaseapp.com',
    storageBucket: 'thoikhoabieuapp-9f53e.firebasestorage.app',
    measurementId: 'G-XZZD8SY2Z5',
  );
}
